server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
sharding:
  jdbc:
    datasource:
      ds0:
        password: Cif_5d6b7c
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/levi?serverTimezone=GMT%2B8
        username: root
      ds1:
        password: Cif_5d6b7c
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shiro?serverTimezone=GMT%2B8
        username: root
      names: ds0,ds1
    config:
      sharding:
        tables:
          t_order:
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order$->{order_id % 2}
            actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
        default-table-strategy: 
          none:
            any: 
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds$->{user_id % 2}